import { randomUUID } from 'node:crypto';
import { connect, TLSSocket } from 'node:tls';

const GMAIL_HOST = 'smtp.gmail.com';
const GMAIL_PORT = 465;
const SMTP_TIMEOUT_MS = 10_000;
const EMAIL_PATTERN = /^[A-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$/i;

export type GmailRecoveryMessage = {
  username: string;
  appPassword: string;
  from: string;
  to: string;
  subject: string;
  html: string;
};

function envelopeEmail(value: string): string {
  if (value.length > 254 || !EMAIL_PATTERN.test(value) || /[\r\n]/.test(value)) {
    throw new Error('Invalid SMTP mailbox');
  }
  return value;
}

export function buildGmailRecoveryMime(input: GmailRecoveryMessage): string {
  const sender = envelopeEmail(input.username);
  const recipient = envelopeEmail(input.to);
  const match = /^([^\r\n<>]{1,90}) <([^\s\r\n<>]+)>$/.exec(input.from);
  if (!match || envelopeEmail(match[2]).toLowerCase() !== sender.toLowerCase()) {
    throw new Error('SMTP sender must match the authorized Gmail account');
  }
  const displayName = match[1].trim();
  if (!displayName || /[\r\n]/.test(input.subject) || input.subject.length > 150) {
    throw new Error('Invalid SMTP mail headers');
  }
  if (Buffer.byteLength(input.html, 'utf8') > 25_000) {
    throw new Error('SMTP mail body exceeds recovery limit');
  }
  const mimeEncode = (value: string) =>
    `=?UTF-8?B?${Buffer.from(value, 'utf8').toString('base64')}?=`;
  const payload = Buffer.from(input.html, 'utf8').toString('base64').match(/.{1,76}/g)?.join('\r\n') ?? '';
  return [
    `From: ${mimeEncode(displayName)} <${sender}>`,
    `To: <${recipient}>`,
    `Subject: ${mimeEncode(input.subject)}`,
    `Date: ${new Date().toUTCString()}`,
    `Message-ID: <${randomUUID()}@knowme-nextech.vercel.app>`,
    'MIME-Version: 1.0',
    'Content-Type: text/html; charset=UTF-8',
    'Content-Transfer-Encoding: base64',
    'Auto-Submitted: auto-generated',
    '',
    payload,
    ''
  ].join('\r\n');
}

class SmtpLineReader {
  private buffered = '';
  private lines: string[] = [];
  private next?: { resolve: (line: string) => void; reject: (cause: Error) => void };
  private failed?: Error;

  constructor(private readonly socket: TLSSocket) {
    socket.on('data', (chunk: Buffer) => {
      this.buffered += chunk.toString('utf8');
      if (this.buffered.length > 32768) {
        socket.destroy(new Error('SMTP response too large'));
        return;
      }
      let end = this.buffered.indexOf('\n');
      while (end !== -1) {
        const line = this.buffered.slice(0, end).replace(/\r$/, '');
        this.buffered = this.buffered.slice(end + 1);
        if (this.next) {
          const listener = this.next;
          this.next = undefined;
          listener.resolve(line);
        } else {
          this.lines.push(line);
        }
        end = this.buffered.indexOf('\n');
      }
    });
    const fail = (error: Error) => {
      this.failed = error;
      if (this.next) {
        const listener = this.next;
        this.next = undefined;
        listener.reject(error);
      }
    };
    socket.on('error', fail);
    socket.on('close', () => fail(new Error('SMTP connection closed')));
    socket.setTimeout(SMTP_TIMEOUT_MS, () => socket.destroy(new Error('SMTP timed out')));
  }

  private line(): Promise<string> {
    if (this.lines.length) return Promise.resolve(this.lines.shift()!);
    if (this.failed) return Promise.reject(this.failed);
    return new Promise((resolve, reject) => { this.next = { resolve, reject }; });
  }

  async expect(...expected: number[]): Promise<void> {
    let code = 0;
    for (let i = 0; i < 35; i++) {
      const line = await this.line();
      const match = /^(\d{3})([ -])/.exec(line);
      if (!match) throw new Error('Unexpected SMTP response');
      code = Number(match[1]);
      if (match[2] === ' ') {
        if (!expected.includes(code)) throw new Error(`SMTP rejected request (${code})`);
        return;
      }
    }
    throw new Error('SMTP response has too many lines');
  }

  async command(value: string, ...expected: number[]) {
    if (/[\r\n]/.test(value)) throw new Error('Invalid SMTP command');
    this.socket.write(value + '\r\n');
    await this.expect(...expected);
  }
}

/** Sends a single transactional recovery message through Gmail implicit TLS.
 *  Requires a Google App Password generated by the mailbox owner. Never logs credentials.
 */
export async function sendGmailRecoveryMail(input: GmailRecoveryMessage): Promise<void> {
  const username = envelopeEmail(input.username);
  const password = input.appPassword.replace(/[ ]/g, '');
  if (password.length < 16 || password.length > 256) throw new Error('Invalid Gmail SMTP authorization');
  const mime = buildGmailRecoveryMime(input);

  const socket = await new Promise<TLSSocket>((resolve, reject) => {
    const client = connect({
      host: GMAIL_HOST,
      port: GMAIL_PORT,
      servername: GMAIL_HOST,
      rejectUnauthorized: true,
      minVersion: 'TLSv1.2'
    });
    client.setTimeout(SMTP_TIMEOUT_MS, () => client.destroy(new Error('SMTP connection timed out')));
    const handleError = (error: Error) => reject(error);
    client.once('error', handleError);
    client.once('secureConnect', () => {
      client.off('error', handleError);
      resolve(client);
    });
  });

  try {
    const smtp = new SmtpLineReader(socket);
    await smtp.expect(220);
    await smtp.command('EHLO knowme-nextech.vercel.app', 250);
    await smtp.command('AUTH PLAIN ' + Buffer.from(`\0${username}\0${password}`).toString('base64'), 235);
    await smtp.command('MAIL FROM:<' + username + '>', 250);
    await smtp.command('RCPT TO:<' + envelopeEmail(input.to) + '>', 250, 251);
    await smtp.command('DATA', 354);
    // Body is strictly base64 MIME, so no line can start with the SMTP terminator dot.
    socket.write(mime + '\r\n.\r\n');
    await smtp.expect(250);
    await smtp.command('QUIT', 221);
  } finally {
    socket.destroy();
  }
}
