FROM node:22.23.2-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32
WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY packages packages
COPY apps/api/package.json apps/api/package.json
RUN pnpm install --filter @knowme/api... --frozen-lockfile

COPY apps/api apps/api
RUN pnpm --filter @knowme/api prisma:generate
RUN pnpm --filter @knowme/api build
RUN chown -R node:node /app

ENV NODE_ENV=production
USER node
EXPOSE 4000
CMD ["pnpm", "--filter", "@knowme/api", "start"]
