FROM node:22-alpine
WORKDIR /app
RUN corepack enable

COPY package.json pnpm-workspace.yaml turbo.json ./
COPY apps/api/package.json apps/api/package.json
RUN pnpm install --filter @knowme/api... --frozen-lockfile=false

COPY apps/api apps/api
RUN pnpm --filter @knowme/api prisma:generate
RUN pnpm --filter @knowme/api build

EXPOSE 4000
CMD ["pnpm", "--filter", "@knowme/api", "start"]
