import { inspectAvatarGlb } from './avatar-glb-parser.domain';
import { AVATAR_EXPRESSION_BLENDSHAPES } from './avatar-facial-expression.domain';

function fixture(){
 const bin=new Uint8Array(1024),v=new DataView(bin.buffer);let o=0;
 const views:any[]=[];const push=(bytes:number,fill:(base:number)=>void)=>{const start=o;fill(start);o+=bytes;views.push({buffer:0,byteOffset:start,byteLength:bytes});return views.length-1;};
 const pos=push(72,b=>{for(let i=0;i<18;i++)v.setFloat32(b+i*4,i/10,true);});
 const normal=push(72,b=>{for(let i=0;i<6;i++)v.setFloat32(b+i*12+4,1,true);});
 const uv=push(48,b=>{for(let i=0;i<12;i++)v.setFloat32(b+i*4,(i%2),true);});
 const joints=push(24,b=>{for(let i=0;i<24;i++)bin[b+i]=i%4;});
 const weights=push(96,b=>{for(let i=0;i<24;i++)v.setFloat32(b+i*4,.25,true);});
 const indices=push(12,b=>{for(let i=0;i<6;i++)v.setUint16(b+i*2,i,true);});
 const texture=push(24,b=>{bin.set([137,80,78,71,13,10,26,10],b);v.setUint32(b+8,13,false);bin.set([73,72,68,82],b+12);v.setUint32(b+16,1,false);v.setUint32(b+20,1,false);});
 const accessors=[{bufferView:indices,componentType:5123,count:6,type:'SCALAR'},{bufferView:pos,componentType:5126,count:6,type:'VEC3'},{bufferView:joints,componentType:5121,count:6,type:'VEC4'},{bufferView:weights,componentType:5126,count:6,type:'VEC4'},{bufferView:normal,componentType:5126,count:6,type:'VEC3'},{bufferView:uv,componentType:5126,count:6,type:'VEC2'}];
 const json:any={asset:{version:'2.0'},buffers:[{byteLength:bin.length}],bufferViews:views,accessors,materials:[{pbrMetallicRoughness:{baseColorTexture:{index:0}}}],textures:[{source:0}],images:[{bufferView:texture,mimeType:'image/png'}],nodes:[{name:'root'},{name:'hips'}],skins:[{joints:[0,1]}],meshes:[{extras:{targetNames:['bodyMass']},primitives:[{indices:0,attributes:{POSITION:1,JOINTS_0:2,WEIGHTS_0:3,NORMAL:4,TEXCOORD_0:5},targets:[{POSITION:1}]}]}]};return{json,bin,texture};
}
function glb(json:any,bin:Uint8Array){const enc=new TextEncoder().encode(JSON.stringify(json)),jp=new Uint8Array(Math.ceil(enc.length/4)*4);jp.set(enc);jp.fill(0x20,enc.length);const bp=new Uint8Array(Math.ceil(bin.length/4)*4);bp.set(bin);const out=new Uint8Array(12+8+jp.length+8+bp.length),view=new DataView(out.buffer);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,out.length,true);view.setUint32(12,jp.length,true);view.setUint32(16,0x4e4f534a,true);out.set(jp,20);const p=20+jp.length;view.setUint32(p,bp.length,true);view.setUint32(p+4,0x004e4942,true);out.set(bp,p+8);return out;}
describe('Avatar GLB binary inspector',()=>{
 it('derives geometry, vertex payload and embedded texture budgets',()=>{const f=fixture(),x=inspectAvatarGlb(glb(f.json,f.bin));expect(x.triangles).toBe(2);expect(x.vertices).toBe(6);expect(x.maxBonesPerVertex).toBe(4);expect(x.normalizedSkinWeights).toBe(true);expect(x.hasNormals).toBe(true);expect(x.hasUv0).toBe(true);expect(x.invalidNumericData).toBe(false);expect(x.joints).toEqual(['root','hips']);expect(x.morphTargets).toEqual(['bodyMass']);expect(x.textureReferencesValid).toBe(true);expect(x.embeddedImages).toBe(true);expect(x.maxTextureWidth).toBe(1);expect(x.maxTextureHeight).toBe(1);expect(x.textureEncodedBytes).toBe(24);expect(x.textureGpuBytes).toBe(4);expect(x.textureMipChainsComplete).toBe(true);});
 it('propagates mesh-bound facial proof and fails closed without a weights animation',()=>{const f=fixture(),mesh=f.json.meshes[0];mesh.extras.targetNames=[...AVATAR_EXPRESSION_BLENDSHAPES];mesh.primitives[0].targets=AVATAR_EXPRESSION_BLENDSHAPES.map(()=>({POSITION:1}));f.json.nodes.push({name:'face',mesh:0});const x=inspectAvatarGlb(glb(f.json,f.bin));expect(x.facialExpressionTargetCount).toBe(AVATAR_EXPRESSION_BLENDSHAPES.length);expect(x.facialExpressionTargets).toEqual([...AVATAR_EXPRESSION_BLENDSHAPES].sort());expect(x.facialExpressionMeshIndices).toEqual([0]);expect(x.facialWeightChannelCount).toBe(0);expect(x.facialValid).toBe(false);expect(x.facialIssues).toContain('Facial expression meshes are not driven by any animation weights channel.');});
 it('certifies Hero DNA and canonical expressions on one mesh with real weights payload',()=>{const f=fixture(),mesh=f.json.meshes[0],names=['bodyMass',...AVATAR_EXPRESSION_BLENDSHAPES];mesh.extras.targetNames=names;mesh.primitives[0].targets=names.map(()=>({POSITION:1}));f.json.nodes.push({name:'heroFace',mesh:0});const faceNode=f.json.nodes.length-1;const timeOffset=348,weightOffset=356,weightCount=names.length*2,view=new DataView(f.bin.buffer);view.setFloat32(timeOffset,0,true);view.setFloat32(timeOffset+4,1,true);for(let i=0;i<weightCount;i++)view.setFloat32(weightOffset+i*4,i<names.length?0:(i===names.length?0.2:0.5),true);const timeView=f.json.bufferViews.push({buffer:0,byteOffset:timeOffset,byteLength:8})-1,weightView=f.json.bufferViews.push({buffer:0,byteOffset:weightOffset,byteLength:weightCount*4})-1,timeAccessor=f.json.accessors.push({bufferView:timeView,componentType:5126,count:2,type:'SCALAR'})-1,weightAccessor=f.json.accessors.push({bufferView:weightView,componentType:5126,count:weightCount,type:'SCALAR'})-1;f.json.animations=[{name:'heroExpressions',samplers:[{input:timeAccessor,output:weightAccessor,interpolation:'LINEAR'}],channels:[{sampler:0,target:{node:faceNode,path:'weights'}}]}];const x=inspectAvatarGlb(glb(f.json,f.bin));expect(x.morphTargets).toEqual([...names].sort());expect(x.facialExpressionTargetCount).toBe(AVATAR_EXPRESSION_BLENDSHAPES.length);expect(x.facialExpressionMeshIndices).toEqual([0]);expect(x.facialWeightChannelCount).toBe(1);expect(x.facialValid).toBe(true);expect(x.facialIssues).toEqual([]);expect(x.animationsValid).toBe(true);expect(x.morphWeightChannelCount).toBe(1);expect(x.animationBinaryValid).toBe(true);expect(x.animationKeyframeCount).toBe(2);expect(x.maxAnimationClipDurationSeconds).toBe(1);});
 it('rejects forged container length',()=>{const f=fixture(),b=glb(f.json,f.bin);new DataView(b.buffer).setUint32(8,b.length-4,true);expect(()=>inspectAvatarGlb(b)).toThrow(/declared length/);});
 it('rejects non triangle primitives',()=>{const f=fixture();f.json.meshes[0].primitives[0].mode=1;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/TRIANGLES/);});
 it('rejects non-indexed runtime geometry',()=>{const f=fixture();delete f.json.meshes[0].primitives[0].indices;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/indexed/);});
 it('counts actual non-zero influences across a second joint set',()=>{const f=fixture(),p=f.json.meshes[0].primitives[0];p.attributes.JOINTS_1=2;p.attributes.WEIGHTS_1=3;expect(inspectAvatarGlb(glb(f.json,f.bin)).maxBonesPerVertex).toBe(8);});
 it('detects non-normalized skin weights from BIN payload',()=>{const f=fixture();new DataView(f.bin.buffer).setFloat32(216,.5,true);expect(inspectAvatarGlb(glb(f.json,f.bin)).normalizedSkinWeights).toBe(false);});
 it('detects NaN vertex payload',()=>{const f=fixture();new DataView(f.bin.buffer).setFloat32(0,Number.NaN,true);expect(inspectAvatarGlb(glb(f.json,f.bin)).invalidNumericData).toBe(true);});
 it('rejects accessor escaping its bufferView',()=>{const f=fixture();f.json.bufferViews[0].byteLength=2;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/exceeds its bufferView/);});
 it('rejects unnamed skin joints',()=>{const f=fixture();delete f.json.nodes[1].name;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/stable node names/);});
 it('rejects anonymous morph targets',()=>{const f=fixture();delete f.json.meshes[0].extras;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/targetNames/);});
 it('detects an external image URI',()=>{const f=fixture();f.json.images[0]={uri:'https://evil.test/skin.png'};const x=inspectAvatarGlb(glb(f.json,f.bin));expect(x.externalImages).toBe(1);expect(x.embeddedImages).toBe(false);});
 it('detects invalid texture source indices',()=>{const f=fixture();f.json.textures[0].source=99;expect(inspectAvatarGlb(glb(f.json,f.bin)).textureReferencesValid).toBe(false);});
 it('rejects MIME spoofing against embedded texture bytes',()=>{const f=fixture();f.json.images[0].mimeType='image/jpeg';expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/JPEG texture has an invalid SOI/);});
 it('does not count bytes outside the image bufferView',()=>{const f=fixture();f.json.bufferViews[f.texture].byteLength=23;expect(()=>inspectAvatarGlb(glb(f.json,f.bin))).toThrow(/PNG texture has an invalid signature or truncated IHDR/);});
 it('detects normal-map usage',()=>{const f=fixture();f.json.materials[0].normalTexture={index:0};expect(inspectAvatarGlb(glb(f.json,f.bin)).normalMappedMaterials).toBe(1);});
 it('allows BasisU but reports unsupported texture extensions',()=>{const f=fixture();f.json.extensionsUsed=['KHR_texture_basisu','KHR_texture_transform'];expect(inspectAvatarGlb(glb(f.json,f.bin)).unsupportedTextureExtensions).toEqual(['KHR_texture_transform']);});
 it('rejects an undeclared KHR_texture_basisu source graph',()=>{const f=fixture();f.json.textures[0].extensions={KHR_texture_basisu:{source:0}};expect(inspectAvatarGlb(glb(f.json,f.bin)).textureReferencesValid).toBe(false);});
 it('requires a BasisU source image to be KTX2 rather than a PNG fallback',()=>{const f=fixture();f.json.extensionsUsed=['KHR_texture_basisu'];f.json.textures[0].extensions={KHR_texture_basisu:{source:0}};expect(inspectAvatarGlb(glb(f.json,f.bin)).textureReferencesValid).toBe(false);});
 it('rejects an out-of-range BasisU source even when a valid fallback exists',()=>{const f=fixture();f.json.extensionsUsed=['KHR_texture_basisu'];f.json.textures[0].extensions={KHR_texture_basisu:{source:99}};expect(inspectAvatarGlb(glb(f.json,f.bin)).textureReferencesValid).toBe(false);});
});
