import { AVATAR_ART_PIPELINE_STAGES } from './avatar-art-production.domain';
import { AVATAR_CATALOG_PRODUCTION_TARGETS, AVATAR_CATALOG_TARGET_COUNT, AvatarCatalogProductionEntry, isAvatarCatalogEntryRuntimeReady, validateAvatarCatalogProductionPlan } from './avatar-catalog-production.domain';
function makePlanEntries(): AvatarCatalogProductionEntry[] { return Object.entries(AVATAR_CATALOG_PRODUCTION_TARGETS).flatMap(([slot,target])=>Array.from({length:target},(_,index)=>({itemKey:`${slot.toLowerCase()}.${index+1}`,slot:slot as AvatarCatalogProductionEntry['slot'],sourceAssetKey:`source.${slot.toLowerCase()}.${index+1}`,variantKey:`variant:${slot.toLowerCase()}:${index+1}`,originalDesign:true as const,completedStages:[]}))); }
function certify(entry: AvatarCatalogProductionEntry): AvatarCatalogProductionEntry { return {...entry,completedStages:[...AVATAR_ART_PIPELINE_STAGES],runtimeGlbUri:'runtime/avatar/outfit-001.glb',runtimeGlbSha256:'a'.repeat(64),runtimeGlbBytes:1_048_576,runtimeCertifiedAt:'2026-09-23T03:00:00.000Z',runtimeManifestSha256:'b'.repeat(64)}; }
describe('Avatar catalog production contract',()=>{
 it('reserves a balanced production backlog of at least 100 original cosmetics',()=>{expect(AVATAR_CATALOG_TARGET_COUNT).toBe(120);expect(AVATAR_CATALOG_PRODUCTION_TARGETS.AVATAR_OUTFIT).toBeGreaterThanOrEqual(30);expect(AVATAR_CATALOG_PRODUCTION_TARGETS.AVATAR_HAIR).toBeGreaterThanOrEqual(20);expect(validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:makePlanEntries()}).entries).toHaveLength(120);});
 it('rejects padding one category while leaving another below its production target',()=>{const entries=makePlanEntries();const withoutHair=entries.filter(e=>e.slot!=='AVATAR_HAIR');const padded=withoutHair.concat(Array.from({length:20},(_,i)=>({...withoutHair[i],itemKey:`padding.${i}`,variantKey:`padding:variant:${i}`})));expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:padded})).toThrow('AVATAR_HAIR requires 20');});
 it('rejects duplicate modular variants masquerading as separate catalog items',()=>{const entries=makePlanEntries();entries[1]={...entries[1],variantKey:entries[0].variantKey};expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries})).toThrow('Duplicate catalog variant key');});
 it('does not treat concept or generated imagery as a runtime 3D asset',()=>{const entry=makePlanEntries()[0];entry.completedStages=['CONCEPT_MULTI_ANGLE'];entry.runtimeGlbUri='runtime/avatar/outfit.glb';entry.runtimeCertifiedAt='2026-09-23T03:00:00.000Z';expect(isAvatarCatalogEntryRuntimeReady(entry)).toBe(false);expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[entry,...makePlanEntries().slice(1)]})).toThrow('cannot claim runtime readiness');});
 it('requires complete art pipeline plus immutable GLB and manifest evidence',()=>{const entry=certify(makePlanEntries()[0]);expect(isAvatarCatalogEntryRuntimeReady(entry)).toBe(true);expect(validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[entry,...makePlanEntries().slice(1)]})).toBeDefined();});
 it('rejects incomplete or malformed certification evidence',()=>{for(const patch of [{runtimeGlbSha256:undefined},{runtimeManifestSha256:undefined},{runtimeGlbBytes:0}]){const entry={...certify(makePlanEntries()[0]),...patch};expect(isAvatarCatalogEntryRuntimeReady(entry)).toBe(false);expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[entry,...makePlanEntries().slice(1)]})).toThrow();}const malformed=certify(makePlanEntries()[0]);malformed.runtimeManifestSha256='not-a-digest';expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[malformed,...makePlanEntries().slice(1)]})).toThrow('runtime manifest requires a valid SHA-256 digest');});
 it('rejects unknown, skipped or reordered artistic gates',()=>{const entries=makePlanEntries();const unknown=entries[0] as AvatarCatalogProductionEntry & {completedStages:string[]};unknown.completedStages=['CONCEPT_MULTI_ANGLE','AI_IMAGE_IS_FINAL_ASSET'];expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[unknown as AvatarCatalogProductionEntry,...entries.slice(1)]})).toThrow('unknown production stage');const skipped={...entries[0],completedStages:[AVATAR_ART_PIPELINE_STAGES[0],AVATAR_ART_PIPELINE_STAGES[2]]} as AvatarCatalogProductionEntry;expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[skipped,...entries.slice(1)]})).toThrow('canonical order without skipping gates');});
 it('keeps certified GLBs inside controlled runtime root',()=>{for(const unsafeUri of ['https://cdn.example.com/avatar/outfit.glb','runtime/avatar/../private/outfit.glb','runtime/avatar/outfit.glb?version=2','runtime/avatar/outfit.glb#tampered','runtime\\avatar\\outfit.glb']){const entry=certify(makePlanEntries()[0]);entry.runtimeGlbUri=unsafeUri;expect(()=>validateAvatarCatalogProductionPlan({revision:'catalog.v1',entries:[entry,...makePlanEntries().slice(1)]})).toThrow('internal GLB under runtime/avatar/');}});
});
