import { AVATAR_ALL_SLOTS, AvatarSlot } from './avatar-universe.domain';

export const AVATAR_ASSET_MANIFEST_VERSION = 1 as const;
export const AVATAR_ASSET_FORMATS = ['GLB', 'GLTF'] as const;
export type AvatarAssetFormat = (typeof AVATAR_ASSET_FORMATS)[number];
export const AVATAR_ASSET_KINDS = ['BASE_BODY','HAIR','FACE','SKIN','CLOTHING','FOOTWEAR','HEADWEAR','ACCESSORY','BACK_ITEM','HAND_ITEM','WEAPON_STYLE','AURA','COMPANION'] as const;
export type AvatarAssetKind = (typeof AVATAR_ASSET_KINDS)[number];
export type AvatarLod = { level:0|1|2; uri:string; triangles:number; vertices:number; downloadBytes:number; sha256:string };
export type AvatarTextureSet = { baseColor?:string; normal?:string; metallicRoughness?:string; occlusion?:string; emissive?:string; maxResolution:512|1024|2048 };
export type AvatarGeometryProfile = { skinned:boolean; hairCards?:boolean; maxBonesPerVertex?:4; };
export type AvatarProductionProvenance = { sourceRevision:string; exportRevision:string; exporter:string; exporterVersion:string; skeletonVersion:string; validatedAt:string };
export type AvatarAssetManifest = { manifestVersion:typeof AVATAR_ASSET_MANIFEST_VERSION; assetKey:string; kind:AvatarAssetKind; slot?:AvatarSlot; format:AvatarAssetFormat; skeletonKey?:string; facialRigKey?:string; materialProfileKey:string; morphTargets:string[]; lods:AvatarLod[]; textures:AvatarTextureSet; geometry?:AvatarGeometryProfile; provenance:AvatarProductionProvenance; pbr:true; originalDesign:true; };

export const AVATAR_CANONICAL_SKELETON='knowme.humanoid.v1';
export const AVATAR_CANONICAL_FACIAL_RIG='knowme.face.v1';
export const AVATAR_BODY_MORPHS=['height','shoulderWidth','torsoLength','muscleDefinition','bodyMass','headScale'] as const;
export const AVATAR_FACE_MORPHS=['jawWidth','cheekboneHeight','noseWidth','noseLength','eyeSize','eyeSpacing','browHeight','lipFullness','earSize'] as const;
export const AVATAR_MOBILE_ASSET_BUDGETS=Object.freeze({maxLod0Triangles:60000,maxLod1Triangles:30000,maxLod2Triangles:12000,maxLod0DownloadBytes:8*1024*1024,maxTextureResolution:2048,maxMorphTargetsPerAsset:32,maxHairLod0Triangles:30000,maxClothingLod0Triangles:40000,maxFootwearLod0Triangles:18000,maxAccessoryLod0Triangles:15000,minLod1TriangleReduction:0.20,minLod2TriangleReductionFromLod1:0.35,maxAnimationClipsPerAsset:24,maxAnimationChannelsPerAsset:256,maxAnimationKeyframesPerAsset:12000,maxAnimationClipDurationSeconds:30});

const SAFE_KEY=/^[a-z0-9][a-z0-9._-]{1,95}$/i;
const SHA256=/^[a-f0-9]{64}$/i;
const SLOT_BY_KIND:Partial<Record<AvatarAssetKind,AvatarSlot[]>>={HAIR:['AVATAR_HAIR'],FACE:['AVATAR_FACE'],SKIN:['AVATAR_SKIN'],CLOTHING:['AVATAR_OUTFIT'],FOOTWEAR:['AVATAR_FOOTWEAR'],HEADWEAR:['AVATAR_HEADWEAR'],ACCESSORY:['AVATAR_ACCESSORY'],BACK_ITEM:['AVATAR_BACK_ITEM'],HAND_ITEM:['AVATAR_HAND_ITEM'],WEAPON_STYLE:['AVATAR_WEAPON_STYLE'],AURA:['AVATAR_AURA'],COMPANION:['AVATAR_COMPANION']};
const SKINNED_KINDS=new Set<AvatarAssetKind>(['BASE_BODY','CLOTHING','FOOTWEAR']);
function assertKey(value:string,label:string){if(!SAFE_KEY.test(value))throw new Error(`Invalid ${label}.`);}
function assertUri(uri:string){if(!(uri.startsWith('https://')||uri.startsWith('asset://')))throw new Error('Avatar asset URI must use https:// or asset://.');}
function assertTextures(input:AvatarAssetManifest){const t=input.textures;if(!t||!t.baseColor)throw new Error('Avatar PBR asset requires a baseColor texture.');for(const uri of [t.baseColor,t.normal,t.metallicRoughness,t.occlusion,t.emissive])if(uri)assertUri(uri);if(['BASE_BODY','SKIN','FACE','CLOTHING','FOOTWEAR','HAIR'].includes(input.kind)&&!t.normal)throw new Error(`${input.kind} requires a normal texture.`);if(['CLOTHING','FOOTWEAR','HEADWEAR','ACCESSORY','BACK_ITEM','HAND_ITEM','WEAPON_STYLE'].includes(input.kind)&&!t.metallicRoughness)throw new Error(`${input.kind} requires a metallicRoughness texture.`);}
function assertKindBudget(input:AvatarAssetManifest,lod0:AvatarLod){const b=AVATAR_MOBILE_ASSET_BUDGETS;const max=input.kind==='HAIR'?b.maxHairLod0Triangles:input.kind==='CLOTHING'?b.maxClothingLod0Triangles:input.kind==='FOOTWEAR'?b.maxFootwearLod0Triangles:['ACCESSORY','HEADWEAR','HAND_ITEM','BACK_ITEM'].includes(input.kind)?b.maxAccessoryLod0Triangles:b.maxLod0Triangles;if(lod0.triangles>max)throw new Error(`${input.kind} exceeds its mobile triangle budget.`);}
function assertRigAndMorphs(input:AvatarAssetManifest){const allowed=SLOT_BY_KIND[input.kind];if(allowed&&(!input.slot||!allowed.includes(input.slot)))throw new Error('Avatar asset kind does not match its Cosmetics slot.');if(SKINNED_KINDS.has(input.kind)){if(input.skeletonKey!==AVATAR_CANONICAL_SKELETON)throw new Error('Skinned avatar asset must use the canonical skeleton.');if(input.geometry?.skinned!==true||input.geometry.maxBonesPerVertex!==4)throw new Error('Skinned avatar asset requires mobile skinning with max 4 bones per vertex.');}if(input.kind==='FACE'&&input.facialRigKey!==AVATAR_CANONICAL_FACIAL_RIG)throw new Error('Face asset must use the canonical facial rig.');if(input.kind==='HAIR'&&input.geometry?.hairCards!==true)throw new Error('Mobile hair assets must use validated hair cards.');if(input.kind==='BASE_BODY'){for(const morph of [...AVATAR_BODY_MORPHS,...AVATAR_FACE_MORPHS])if(!input.morphTargets.includes(morph))throw new Error(`Base body is missing required morph target ${morph}.`);}if(input.kind==='CLOTHING'){for(const morph of AVATAR_BODY_MORPHS)if(!input.morphTargets.includes(morph))throw new Error(`Clothing is missing required body morph target ${morph}.`);}}
function assertProvenance(input:AvatarAssetManifest){const p=input.provenance;if(!p)throw new Error('Avatar runtime asset requires production provenance.');for(const [value,label] of [[p.sourceRevision,'source revision'],[p.exportRevision,'export revision'],[p.exporter,'exporter'],[p.exporterVersion,'exporter version']] as const)assertKey(value,label);if(p.skeletonVersion!==AVATAR_CANONICAL_SKELETON)throw new Error('Avatar provenance skeleton version must match the canonical skeleton.');const timestamp=Date.parse(p.validatedAt);if(!Number.isFinite(timestamp))throw new Error('Avatar provenance requires a valid validation timestamp.');if(timestamp>Date.now()+5*60*1000)throw new Error('Avatar provenance validation timestamp cannot be in the future.');}

export function validateAvatarAssetManifest(input:AvatarAssetManifest):AvatarAssetManifest{
 if(input.manifestVersion!==AVATAR_ASSET_MANIFEST_VERSION)throw new Error('Unsupported avatar asset manifest version.');if(!AVATAR_ASSET_FORMATS.includes(input.format))throw new Error('Unsupported avatar asset format.');if(!AVATAR_ASSET_KINDS.includes(input.kind))throw new Error('Unsupported avatar asset kind.');assertKey(input.assetKey,'asset key');assertKey(input.materialProfileKey,'material profile key');if(input.slot&&!AVATAR_ALL_SLOTS.includes(input.slot))throw new Error('Unsupported avatar slot.');if(input.skeletonKey)assertKey(input.skeletonKey,'skeleton key');if(input.facialRigKey)assertKey(input.facialRigKey,'facial rig key');if(input.pbr!==true||input.originalDesign!==true)throw new Error('Avatar runtime assets must be PBR and original designs.');assertProvenance(input);
 if(!Array.isArray(input.lods)||input.lods.length!==3)throw new Error('Avatar assets require exactly LOD0, LOD1 and LOD2.');const sorted=[...input.lods].sort((a,b)=>a.level-b.level);if(sorted.some((lod,index)=>lod.level!==index))throw new Error('Avatar LOD levels must be 0, 1 and 2.');for(const lod of sorted){assertUri(lod.uri);if(!SHA256.test(lod.sha256))throw new Error('Avatar LOD requires a valid SHA-256 checksum.');if(!Number.isSafeInteger(lod.triangles)||lod.triangles<=0||!Number.isSafeInteger(lod.vertices)||lod.vertices<=0||!Number.isSafeInteger(lod.downloadBytes)||lod.downloadBytes<=0)throw new Error('Invalid avatar LOD metrics.');}
 const b=AVATAR_MOBILE_ASSET_BUDGETS;if(sorted[0].triangles>b.maxLod0Triangles||sorted[1].triangles>b.maxLod1Triangles||sorted[2].triangles>b.maxLod2Triangles)throw new Error('Avatar asset exceeds mobile triangle budget.');assertKindBudget(input,sorted[0]);if(sorted[0].downloadBytes>b.maxLod0DownloadBytes)throw new Error('Avatar asset exceeds mobile download budget.');if(sorted[1].triangles>=sorted[0].triangles||sorted[2].triangles>=sorted[1].triangles)throw new Error('Avatar LOD triangle counts must strictly decrease.');if(sorted[1].triangles>Math.floor(sorted[0].triangles*(1-b.minLod1TriangleReduction))||sorted[2].triangles>Math.floor(sorted[1].triangles*(1-b.minLod2TriangleReductionFromLod1)))throw new Error('Avatar LOD chain does not reduce geometry enough for mobile runtime.');if(![512,1024,2048].includes(input.textures?.maxResolution)||input.textures.maxResolution>b.maxTextureResolution)throw new Error('Avatar texture resolution exceeds mobile budget.');if(!Array.isArray(input.morphTargets)||input.morphTargets.length>b.maxMorphTargetsPerAsset)throw new Error('Too many morph targets for avatar asset.');if(new Set(input.morphTargets).size!==input.morphTargets.length)throw new Error('Duplicate avatar morph targets are not allowed.');for(const morph of input.morphTargets)assertKey(morph,'morph target');assertTextures(input);assertRigAndMorphs(input);return input;
}
export function assertAvatarSkeletonCompatibility(baseSkeletonKey:string,asset:AvatarAssetManifest){if(asset.skeletonKey&&asset.skeletonKey!==baseSkeletonKey)throw new Error('Avatar asset skeleton is incompatible with the equipped base body.');return true;}
