export type AvatarEmbeddedImageInspection={mimeType:'image/png'|'image/jpeg'|'image/ktx2';width:number;height:number;mipLevels:number;encodedBytes:number;estimatedRgba8GpuBytes:number};

const PNG=Uint8Array.from([137,80,78,71,13,10,26,10]);
const KTX2=Uint8Array.from([0xab,0x4b,0x54,0x58,0x20,0x32,0x30,0xbb,0x0d,0x0a,0x1a,0x0a]);
function same(a:Uint8Array,b:Uint8Array,offset=0){return b.every((v,i)=>a[offset+i]===v);}
function positive(v:number,label:string){if(!Number.isSafeInteger(v)||v<=0)throw new Error(`Avatar texture has invalid ${label}.`);return v;}
function rgbaMipBytes(width:number,height:number,levels:number){let total=0,w=width,h=height;for(let i=0;i<levels;i++){total+=w*h*4;w=Math.max(1,Math.floor(w/2));h=Math.max(1,Math.floor(h/2));}if(!Number.isSafeInteger(total))throw new Error('Avatar texture decoded size exceeds safe integer range.');return total;}
function fullMipCount(w:number,h:number){return Math.floor(Math.log2(Math.max(w,h)))+1;}
function png(bytes:Uint8Array):AvatarEmbeddedImageInspection{if(bytes.length<24||!same(bytes,PNG))throw new Error('Embedded PNG texture has an invalid signature or truncated IHDR.');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(v.getUint32(8,false)!==13||String.fromCharCode(...bytes.subarray(12,16))!=='IHDR')throw new Error('Embedded PNG texture must start with IHDR.');const width=positive(v.getUint32(16,false),'PNG width'),height=positive(v.getUint32(20,false),'PNG height');return{mimeType:'image/png',width,height,mipLevels:1,encodedBytes:bytes.length,estimatedRgba8GpuBytes:rgbaMipBytes(width,height,1)};}
function jpeg(bytes:Uint8Array):AvatarEmbeddedImageInspection{if(bytes.length<4||bytes[0]!==0xff||bytes[1]!==0xd8)throw new Error('Embedded JPEG texture has an invalid SOI marker.');let p=2;while(p+3<bytes.length){if(bytes[p++]!==0xff)throw new Error('Embedded JPEG texture contains a malformed marker stream.');while(p<bytes.length&&bytes[p]===0xff)p++;const marker=bytes[p++];if(marker===0xd9||marker===0xda)break;if(marker===0x01||(marker>=0xd0&&marker<=0xd7))continue;if(p+2>bytes.length)break;const len=(bytes[p]<<8)|bytes[p+1];if(len<2||p+len>bytes.length)throw new Error('Embedded JPEG texture contains a truncated segment.');if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)){if(len<7)throw new Error('Embedded JPEG SOF segment is truncated.');const height=positive((bytes[p+3]<<8)|bytes[p+4],'JPEG height'),width=positive((bytes[p+5]<<8)|bytes[p+6],'JPEG width');return{mimeType:'image/jpeg',width,height,mipLevels:1,encodedBytes:bytes.length,estimatedRgba8GpuBytes:rgbaMipBytes(width,height,1)};}p+=len;}throw new Error('Embedded JPEG texture has no supported SOF dimensions.');}
function ktx2(bytes:Uint8Array):AvatarEmbeddedImageInspection{if(bytes.length<68||!same(bytes,KTX2))throw new Error('Embedded KTX2 texture has an invalid identifier or truncated header.');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),width=positive(v.getUint32(20,true),'KTX2 width'),height=positive(v.getUint32(24,true),'KTX2 height'),depth=v.getUint32(28,true),layers=v.getUint32(32,true),faces=v.getUint32(36,true),levels=positive(v.getUint32(40,true),'KTX2 level count');if(depth>1||layers>1||faces!==1)throw new Error('Avatar KTX2 textures must be single-layer 2D textures.');if(levels>fullMipCount(width,height))throw new Error('Avatar KTX2 texture declares impossible mip levels.');const levelIndexEnd=68+levels*24;if(levelIndexEnd>bytes.length)throw new Error('Avatar KTX2 level index is truncated.');return{mimeType:'image/ktx2',width,height,mipLevels:levels,encodedBytes:bytes.length,estimatedRgba8GpuBytes:rgbaMipBytes(width,height,levels)};}
export function inspectAvatarEmbeddedImage(bytes:Uint8Array,mimeType:string):AvatarEmbeddedImageInspection{if(mimeType==='image/png')return png(bytes);if(mimeType==='image/jpeg')return jpeg(bytes);if(mimeType==='image/ktx2')return ktx2(bytes);throw new Error(`Unsupported embedded avatar texture MIME type ${mimeType}.`);}
