import { AVATAR_ALL_SLOTS, AvatarSlot } from './avatar-universe.domain';

export const AVATAR_ASSET_MANIFEST_VERSION = 1 as const;
export const AVATAR_ASSET_FORMATS = ['GLB', 'GLTF'] as const;
export type AvatarAssetFormat = (typeof AVATAR_ASSET_FORMATS)[number];
export const AVATAR_ASSET_KINDS = ['BASE_BODY','HAIR','FACE','SKIN','CLOTHING','FOOTWEAR','HEADWEAR','ACCESSORY','BACK_ITEM','HAND_ITEM','WEAPON_STYLE','AURA','COMPANION'] as const;
export type AvatarAssetKind = (typeof AVATAR_ASSET_KINDS)[number];
export const AVATAR_TEXTURE_RUNTIME_FORMATS=['KTX2'] as const;
export type AvatarTextureRuntimeFormat=(typeof AVATAR_TEXTURE_RUNTIME_FORMATS)[number];
export const AVATAR_TEXTURE_COMPRESSIONS=['BASISU_ETC1S','BASISU_UASTC'] as const;
export type AvatarTextureCompression=(typeof AVATAR_TEXTURE_COMPRESSIONS)[number];
export type AvatarLod = { level:0|1|2; uri:string; triangles:number; vertices:number; downloadBytes:number };
export type AvatarTextureSet = { baseColor?:string; normal?:string; metallicRoughness?:string; occlusion?:string; emissive?:string; maxResolution:512|1024|2048; runtimeFormat?:AvatarTextureRuntimeFormat; compression?:AvatarTextureCompression };
export type AvatarGeometryProfile = { skinned:boolean; hairCards?:boolean; maxBonesPerVertex?:4; };
export type AvatarAssetManifest = { manifestVersion:typeof AVATAR_ASSET_MANIFEST_VERSION; assetKey:string; kind:AvatarAssetKind; slot?:AvatarSlot; format:AvatarAssetFormat; skeletonKey?:string; facialRigKey?:string; materialProfileKey:string; morphTargets:string[]; lods:AvatarLod[]; textures:AvatarTextureSet; geometry?:AvatarGeometryProfile; pbr:true; originalDesign:true; };

export const AVATAR_CANONICAL_SKELETON='knowme.humanoid.v1';
export const AVATAR_CANONICAL_FACIAL_RIG='knowme.face.v1';
export const AVATAR_BODY_MORPHS=['height','shoulderWidth','torsoLength','muscleDefinition','bodyMass','headScale'] as const;
export const AVATAR_FACE_MORPHS=['jawWidth','cheekboneHeight','noseWidth','noseLength','eyeSize','eyeSpacing','browHeight','lipFullness','earSize'] as const;
/** Runtime expression blendshapes guaranteed by every certified FACE asset. Keep stable for animation retargeting. */
export const AVATAR_EXPRESSION_MORPHS=['blinkLeft','blinkRight','browDownLeft','browDownRight','browInnerUp','jawOpen','mouthSmileLeft','mouthSmileRight','mouthFrownLeft','mouthFrownRight','mouthPucker','mouthClose'] as const;
export const AVATAR_MOBILE_ASSET_BUDGETS=Object.freeze({maxLod0Triangles:60000,maxLod1Triangles:30000,maxLod2Triangles:12000,maxLod0DownloadBytes:8*1024*1024,maxLod1DownloadBytes:4*1024*1024,maxLod2DownloadBytes:2*1024*1024,maxTextureResolution:2048,maxMorphTargetsPerAsset:32,maxHairLod0Triangles:30000,maxClothingLod0Triangles:40000,maxFootwearLod0Triangles:18000,maxAccessoryLod0Triangles:15000});
export const AVATAR_LOD_MIN_REDUCTION_FROM_PREVIOUS = [0, 0.25, 0.50] as const;

const SAFE_KEY=/^[a-z0-9][a-z0-9._-]{1,95}$/i;
const SLOT_BY_KIND:Partial<Record<AvatarAssetKind,AvatarSlot[]>>={HAIR:['AVATAR_HAIR'],FACE:['AVATAR_FACE'],SKIN:['AVATAR_SKIN'],CLOTHING:['AVATAR_OUTFIT'],FOOTWEAR:['AVATAR_FOOTWEAR'],HEADWEAR:['AVATAR_HEADWEAR'],ACCESSORY:['AVATAR_ACCESSORY'],BACK_ITEM:['AVATAR_BACK_ITEM'],HAND_ITEM:['AVATAR_HAND_ITEM'],WEAPON_STYLE:['AVATAR_WEAPON_STYLE'],AURA:['AVATAR_AURA'],COMPANION:['AVATAR_COMPANION']};
const SKINNED_KINDS=new Set<AvatarAssetKind>(['BASE_BODY','CLOTHING','FOOTWEAR']);
const MANIFEST_KEYS=new Set(['manifestVersion','assetKey','kind','slot','format','skeletonKey','facialRigKey','materialProfileKey','morphTargets','lods','textures','geometry','pbr','originalDesign']);
const LOD_KEYS=new Set(['level','uri','triangles','vertices','downloadBytes']);
const TEXTURE_KEYS=new Set(['baseColor','normal','metallicRoughness','occlusion','emissive','maxResolution','runtimeFormat','compression']);
const GEOMETRY_KEYS=new Set(['skinned','hairCards','maxBonesPerVertex']);
function assertPlainObject(value:unknown,label:string):asserts value is Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label} must be an object.`);}
function assertOnlyKnownKeys(value:Record<string,unknown>,allowed:ReadonlySet<string>,label:string){for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`Unknown ${label} field: ${key}`);}
function assertKey(value:string,label:string){if(!SAFE_KEY.test(value))throw new Error(`Invalid ${label}.`);}
function assertUri(uri:string){if(typeof uri!=='string'||!(uri.startsWith('https://')||uri.startsWith('asset://')))throw new Error('Avatar asset URI must use https:// or asset://.');}
function assertTextureEncoding(input:AvatarTextureSet){const hasFormat=input.runtimeFormat!==undefined,hasCompression=input.compression!==undefined;if(hasFormat!==hasCompression)throw new Error('Avatar runtime texture format and compression must be declared together.');if(hasFormat&&(!AVATAR_TEXTURE_RUNTIME_FORMATS.includes(input.runtimeFormat!)||!AVATAR_TEXTURE_COMPRESSIONS.includes(input.compression!)))throw new Error('Unsupported avatar runtime texture encoding.');}
function assertTextures(input:AvatarAssetManifest){const t=input.textures;if(!t||!t.baseColor)throw new Error('Avatar PBR asset requires a baseColor texture.');for(const uri of [t.baseColor,t.normal,t.metallicRoughness,t.occlusion,t.emissive])if(uri)assertUri(uri);assertTextureEncoding(t);if(['BASE_BODY','SKIN','FACE','CLOTHING','FOOTWEAR','HAIR'].includes(input.kind)&&!t.normal)throw new Error(`${input.kind} requires a normal texture.`);if(['CLOTHING','FOOTWEAR','HEADWEAR','ACCESSORY','BACK_ITEM','HAND_ITEM','WEAPON_STYLE'].includes(input.kind)&&!t.metallicRoughness)throw new Error(`${input.kind} requires a metallicRoughness texture.`);}
function assertKindBudget(input:AvatarAssetManifest,lod0:AvatarLod){const b=AVATAR_MOBILE_ASSET_BUDGETS;const max=input.kind==='HAIR'?b.maxHairLod0Triangles:input.kind==='CLOTHING'?b.maxClothingLod0Triangles:input.kind==='FOOTWEAR'?b.maxFootwearLod0Triangles:['ACCESSORY','HEADWEAR','HAND_ITEM','BACK_ITEM'].includes(input.kind)?b.maxAccessoryLod0Triangles:b.maxLod0Triangles;if(lod0.triangles>max)throw new Error(`${input.kind} exceeds its mobile triangle budget.`);}
function assertLodReduction(lods:AvatarLod[]){if(new Set(lods.map(lod=>lod.uri)).size!==lods.length)throw new Error('Avatar LODs must reference distinct runtime payloads.');for(let index=1;index<lods.length;index++){const minimum=AVATAR_LOD_MIN_REDUCTION_FROM_PREVIOUS[index];const maxRatio=1-minimum;if(lods[index].triangles>Math.floor(lods[index-1].triangles*maxRatio))throw new Error(`Avatar LOD${index} triangles must reduce by at least ${minimum*100}% from LOD${index-1}.`);if(lods[index].vertices>Math.floor(lods[index-1].vertices*maxRatio))throw new Error(`Avatar LOD${index} vertices must reduce by at least ${minimum*100}% from LOD${index-1}.`);if(lods[index].downloadBytes>=lods[index-1].downloadBytes)throw new Error(`Avatar LOD${index} download payload must be smaller than LOD${index-1}.`);}}
function assertRequiredMorphs(input:AvatarAssetManifest,required:readonly string[],label:string){for(const morph of required)if(!input.morphTargets.includes(morph))throw new Error(`${label} is missing required morph target ${morph}.`);}
function assertRigAndMorphs(input:AvatarAssetManifest){const allowed=SLOT_BY_KIND[input.kind];if(allowed&&(!input.slot||!allowed.includes(input.slot)))throw new Error('Avatar asset kind does not match its Cosmetics slot.');if(SKINNED_KINDS.has(input.kind)){if(input.skeletonKey!==AVATAR_CANONICAL_SKELETON)throw new Error('Skinned avatar asset must use the canonical skeleton.');if(input.geometry?.skinned!==true||input.geometry.maxBonesPerVertex!==4)throw new Error('Skinned avatar asset requires mobile skinning with max 4 bones per vertex.');}if(input.kind==='FACE'){if(input.facialRigKey!==AVATAR_CANONICAL_FACIAL_RIG)throw new Error('Face asset must use the canonical facial rig.');assertRequiredMorphs(input,AVATAR_FACE_MORPHS,'Face asset');assertRequiredMorphs(input,AVATAR_EXPRESSION_MORPHS,'Face asset');}if(input.kind==='HAIR'&&input.geometry?.hairCards!==true)throw new Error('Mobile hair assets must use validated hair cards.');if(input.kind==='BASE_BODY')assertRequiredMorphs(input,[...AVATAR_BODY_MORPHS,...AVATAR_FACE_MORPHS],'Base body');if(input.kind==='CLOTHING')assertRequiredMorphs(input,AVATAR_BODY_MORPHS,'Clothing');}

/** Validates untrusted manifest data and returns a fresh canonical projection. */
export function validateAvatarAssetManifest(input:AvatarAssetManifest):AvatarAssetManifest{
 assertPlainObject(input,'Avatar asset manifest');assertOnlyKnownKeys(input as unknown as Record<string,unknown>,MANIFEST_KEYS,'avatar asset manifest');
 if(input.manifestVersion!==AVATAR_ASSET_MANIFEST_VERSION)throw new Error('Unsupported avatar asset manifest version.');if(!AVATAR_ASSET_FORMATS.includes(input.format))throw new Error('Unsupported avatar asset format.');if(!AVATAR_ASSET_KINDS.includes(input.kind))throw new Error('Unsupported avatar asset kind.');assertKey(input.assetKey,'asset key');assertKey(input.materialProfileKey,'material profile key');if(input.slot&&!AVATAR_ALL_SLOTS.includes(input.slot))throw new Error('Unsupported avatar slot.');if(input.skeletonKey)assertKey(input.skeletonKey,'skeleton key');if(input.facialRigKey)assertKey(input.facialRigKey,'facial rig key');if(input.pbr!==true||input.originalDesign!==true)throw new Error('Avatar runtime assets must be PBR and original designs.');
 if(!Array.isArray(input.lods)||input.lods.length!==3)throw new Error('Avatar assets require exactly LOD0, LOD1 and LOD2.');for(const lod of input.lods){assertPlainObject(lod,'Avatar LOD');assertOnlyKnownKeys(lod as unknown as Record<string,unknown>,LOD_KEYS,'avatar LOD');}const sorted=[...input.lods].sort((a,b)=>a.level-b.level);if(sorted.some((lod,index)=>lod.level!==index))throw new Error('Avatar LOD levels must be 0, 1 and 2.');for(const lod of sorted){assertUri(lod.uri);if(!Number.isSafeInteger(lod.triangles)||lod.triangles<=0||!Number.isSafeInteger(lod.vertices)||lod.vertices<=0||!Number.isSafeInteger(lod.downloadBytes)||lod.downloadBytes<=0)throw new Error('Invalid avatar LOD metrics.');}
 assertPlainObject(input.textures,'Avatar textures');assertOnlyKnownKeys(input.textures as unknown as Record<string,unknown>,TEXTURE_KEYS,'avatar texture');if(input.geometry!==undefined){assertPlainObject(input.geometry,'Avatar geometry');assertOnlyKnownKeys(input.geometry as unknown as Record<string,unknown>,GEOMETRY_KEYS,'avatar geometry');}
 const b=AVATAR_MOBILE_ASSET_BUDGETS;if(sorted[0].triangles>b.maxLod0Triangles||sorted[1].triangles>b.maxLod1Triangles||sorted[2].triangles>b.maxLod2Triangles)throw new Error('Avatar asset exceeds mobile triangle budget.');assertKindBudget(input,sorted[0]);if(sorted[0].downloadBytes>b.maxLod0DownloadBytes||sorted[1].downloadBytes>b.maxLod1DownloadBytes||sorted[2].downloadBytes>b.maxLod2DownloadBytes)throw new Error('Avatar asset exceeds mobile download budget.');assertLodReduction(sorted);if(![512,1024,2048].includes(input.textures.maxResolution)||input.textures.maxResolution>b.maxTextureResolution)throw new Error('Avatar texture resolution exceeds mobile budget.');if(!Array.isArray(input.morphTargets)||input.morphTargets.length>b.maxMorphTargetsPerAsset)throw new Error('Too many morph targets for avatar asset.');if(new Set(input.morphTargets).size!==input.morphTargets.length)throw new Error('Duplicate avatar morph targets are not allowed.');for(const morph of input.morphTargets)assertKey(morph,'morph target');assertTextures(input);assertRigAndMorphs(input);
 const textures:AvatarTextureSet={maxResolution:input.textures.maxResolution};for(const key of ['baseColor','normal','metallicRoughness','occlusion','emissive'] as const)if(input.textures[key]!==undefined)textures[key]=input.textures[key];if(input.textures.runtimeFormat!==undefined)textures.runtimeFormat=input.textures.runtimeFormat;if(input.textures.compression!==undefined)textures.compression=input.textures.compression;
 const result:AvatarAssetManifest={manifestVersion:AVATAR_ASSET_MANIFEST_VERSION,assetKey:input.assetKey,kind:input.kind,format:input.format,materialProfileKey:input.materialProfileKey,morphTargets:[...input.morphTargets],lods:sorted.map(lod=>({level:lod.level,uri:lod.uri,triangles:lod.triangles,vertices:lod.vertices,downloadBytes:lod.downloadBytes})),textures,pbr:true,originalDesign:true};
 if(input.slot!==undefined)result.slot=input.slot;if(input.skeletonKey!==undefined)result.skeletonKey=input.skeletonKey;if(input.facialRigKey!==undefined)result.facialRigKey=input.facialRigKey;if(input.geometry!==undefined){result.geometry={skinned:input.geometry.skinned};if(input.geometry.hairCards!==undefined)result.geometry.hairCards=input.geometry.hairCards;if(input.geometry.maxBonesPerVertex!==undefined)result.geometry.maxBonesPerVertex=input.geometry.maxBonesPerVertex;}
 return result;
}
export function assertAvatarSkeletonCompatibility(baseSkeletonKey:string,asset:AvatarAssetManifest){if(asset.skeletonKey&&asset.skeletonKey!==baseSkeletonKey)throw new Error('Avatar asset skeleton is incompatible with the equipped base body.');return true;}
