import { inspectAvatarEmbeddedImage } from './avatar-image-inspection.domain';

function png(w=1024,h=512){const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10]);const v=new DataView(b.buffer);v.setUint32(8,13,false);b.set([73,72,68,82],12);v.setUint32(16,w,false);v.setUint32(20,h,false);return b;}
function jpeg(w=640,h=480){return Uint8Array.from([0xff,0xd8,0xff,0xc0,0,17,8,h>>8,h&255,w>>8,w&255,3,1,0x11,0,2,0x11,0,3,0x11,0,0xff,0xd9]);}
function ktx2(w=1024,h=1024,levels=11,profile:'ETC1S'|'UASTC'='ETC1S'){const indexEnd=80+levels*24,dfdOffset=indexEnd,dfdLength=28,sgdLength=profile==='ETC1S'?16:0,sgdOffset=sgdLength?dfdOffset+dfdLength:0,payloadStart=dfdOffset+dfdLength+sgdLength,payloadBytes=levels*8,b=new Uint8Array(payloadStart+payloadBytes);b.set([0xab,0x4b,0x54,0x58,0x20,0x32,0x30,0xbb,0x0d,0x0a,0x1a,0x0a]);const v=new DataView(b.buffer);v.setUint32(12,0,true);v.setUint32(16,1,true);v.setUint32(20,w,true);v.setUint32(24,h,true);v.setUint32(28,0,true);v.setUint32(32,0,true);v.setUint32(36,1,true);v.setUint32(40,levels,true);v.setUint32(44,profile==='ETC1S'?1:0,true);v.setUint32(48,dfdOffset,true);v.setUint32(52,dfdLength,true);v.setUint32(64,sgdOffset,true);v.setUint32(72,sgdLength,true);v.setUint32(dfdOffset,dfdLength,true);v.setUint16(dfdOffset+8,2,true);v.setUint16(dfdOffset+10,24,true);v.setUint8(dfdOffset+12,profile==='ETC1S'?163:166);v.setUint8(dfdOffset+13,1);v.setUint8(dfdOffset+14,2);for(let i=0;i<levels;i++){const p=80+i*24,offset=payloadStart+i*8;v.setUint32(p,offset,true);v.setUint32(p+8,8,true);v.setUint32(p+16,8,true);}return b;}
describe('Avatar embedded texture inspection',()=>{
 it('reads PNG dimensions from the real IHDR header',()=>{const x=inspectAvatarEmbeddedImage(png(),'image/png');expect(x).toMatchObject({width:1024,height:512,mipLevels:1,estimatedRgba8GpuBytes:1024*512*4});});
 it('reads JPEG dimensions from SOF instead of metadata supplied by a producer',()=>{const x=inspectAvatarEmbeddedImage(jpeg(),'image/jpeg');expect(x).toMatchObject({width:640,height:480,mipLevels:1});});
 it('reads KTX2 dimensions, mip count and ETC1S/BasisLZ profile',()=>{const x=inspectAvatarEmbeddedImage(ktx2(),'image/ktx2');expect(x.width).toBe(1024);expect(x.height).toBe(1024);expect(x.mipLevels).toBe(11);expect(x.estimatedRgba8GpuBytes).toBeGreaterThan(1024*1024*4);expect(x.ktx2).toEqual({vkFormat:0,supercompressionScheme:1,levelPayloadBytes:88,profile:'ETC1S',dfdTransferFunction:2,dfdColorModel:163,hasSgd:true});});
 it('accepts UASTC with vkFormat UNDEFINED and no supercompression',()=>{const x=inspectAvatarEmbeddedImage(ktx2(256,256,9,'UASTC'),'image/ktx2');expect(x.ktx2).toMatchObject({profile:'UASTC',supercompressionScheme:0,hasSgd:false});});
 it('rejects a forged PNG MIME over arbitrary bytes',()=>expect(()=>inspectAvatarEmbeddedImage(new Uint8Array(24),'image/png')).toThrow(/PNG/));
 it('rejects a JPEG without SOF dimensions',()=>expect(()=>inspectAvatarEmbeddedImage(Uint8Array.from([0xff,0xd8,0xff,0xd9]),'image/jpeg')).toThrow(/SOF/));
 it('rejects impossible KTX2 mip counts',()=>expect(()=>inspectAvatarEmbeddedImage(ktx2(4,4,8),'image/ktx2')).toThrow(/mip/));
 it('rejects truncated KTX2 level indices',()=>{const b=ktx2(1024,1024,11).subarray(0,80+10*24);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/level index|outside/);});
 it('rejects cubemap/array KTX2 payloads for avatar materials',()=>{const b=ktx2();new DataView(b.buffer).setUint32(36,6,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/single-layer 2D/);});
 it('rejects KTX2 levels that point outside the embedded image',()=>{const b=ktx2(16,16,5),v=new DataView(b.buffer);v.setUint32(80,b.length+4,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/outside/);});
 it('rejects KTX2 levels overlapping the header/index',()=>{const b=ktx2(16,16,5),v=new DataView(b.buffer);v.setUint32(80,80,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/overlaps/);});
 it('rejects overlapping KTX2 mip payloads',()=>{const b=ktx2(16,16,5),v=new DataView(b.buffer),first=v.getUint32(80,true);v.setUint32(104,first+4,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/overlap/);});
 it('rejects unsupported KTX2 supercompression',()=>{const b=ktx2(),v=new DataView(b.buffer);v.setUint32(44,99,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/supercompression/);});
 it('rejects ETC1S BasisLZ without its global data',()=>{const b=ktx2(),v=new DataView(b.buffer);v.setUint32(64,0,true);v.setUint32(72,0,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/requires SGD/);});
 it('rejects malformed DFD ranges',()=>{const b=ktx2(),v=new DataView(b.buffer);v.setUint32(52,8,true);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/DFD/);});
 it('rejects an unspecified DFD transfer function',()=>{const b=ktx2(),v=new DataView(b.buffer),dfd=v.getUint32(48,true);v.setUint8(dfd+14,0);expect(()=>inspectAvatarEmbeddedImage(b,'image/ktx2')).toThrow(/LINEAR or SRGB/);});
 it('rejects unsupported image MIME types',()=>expect(()=>inspectAvatarEmbeddedImage(png(),'image/webp')).toThrow(/Unsupported/));
});
