import {HeroRuntimeEvidenceAuthority,HeroRuntimeEvidenceRecord,HeroRuntimeEvidenceStore} from './hero-runtime-evidence-v22.domain';
import {HeroAndroidSourceResult} from './hero-runtime-android-source-v21.domain';

class MemoryStore implements HeroRuntimeEvidenceStore{records:HeroRuntimeEvidenceRecord[]=[];async findBySessionId(id:string){return this.records.find(x=>x.sessionId===id)??null;}async findBySourceEvidenceSha256(d:string){return this.records.find(x=>x.sourceEvidenceSha256===d)??null;}async append(r:HeroRuntimeEvidenceRecord){if(await this.findBySessionId(r.sessionId)||await this.findBySourceEvidenceSha256(r.sourceEvidenceSha256))throw new Error('unique');this.records.push({...r});}async consume(d:string,id:string,at:number){const r=await this.findBySourceEvidenceSha256(d);if(!r||r.consumedAtMs!==null)return false;r.consumedAtMs=at;r.certificationId=id;return true;}}
const result=(sessionId='session-a',source='a'.repeat(64),bundle='b'.repeat(64))=>({identity:{sessionId,build:{runtimeBundleSha256:bundle,appVersion:'1.0.0',commitSha:'c'.repeat(40)}},sourceEvidenceSha256:source,evidenceSha256:'d'.repeat(64),endedAtMs:1000} as unknown as HeroAndroidSourceResult);

describe('Hero runtime evidence authority v22',()=>{
 it('appends accepted evidence and is idempotent for the exact same session/digest',async()=>{const store=new MemoryStore();const authority=new HeroRuntimeEvidenceAuthority(store,()=>1100);const first=await authority.accept(result());const second=await authority.accept(result());expect(store.records).toHaveLength(1);expect(second).toEqual(first);expect(authority.auditDigest(first)).toMatch(/^[a-f0-9]{64}$/);});
 it('rejects rebinding a session id to different source evidence',async()=>{const store=new MemoryStore();const authority=new HeroRuntimeEvidenceAuthority(store,()=>1100);await authority.accept(result());await expect(authority.accept(result('session-a','e'.repeat(64)))).rejects.toThrow(/different evidence/);});
 it('rejects rebinding one source evidence digest to another session',async()=>{const store=new MemoryStore();const authority=new HeroRuntimeEvidenceAuthority(store,()=>1100);await authority.accept(result());await expect(authority.accept(result('session-b'))).rejects.toThrow(/another session/);});
 it('consumes evidence once and binds it to the certified Hero bundle',async()=>{const store=new MemoryStore();let now=1100;const authority=new HeroRuntimeEvidenceAuthority(store,()=>now++);const accepted=await authority.accept(result());const consumed=await authority.consume(accepted.sourceEvidenceSha256,accepted.runtimeBundleSha256,'cert-1');expect(consumed.certificationId).toBe('cert-1');await expect(authority.consume(accepted.sourceEvidenceSha256,accepted.runtimeBundleSha256,'cert-2')).rejects.toThrow(/already been consumed/);});
 it('refuses consumption for a different Hero bundle',async()=>{const store=new MemoryStore();const authority=new HeroRuntimeEvidenceAuthority(store,()=>1100);const accepted=await authority.accept(result());await expect(authority.consume(accepted.sourceEvidenceSha256,'f'.repeat(64),'cert-1')).rejects.toThrow(/another Hero bundle/);});
 it('rejects malformed digests and acceptance before the measured run ended',async()=>{const store=new MemoryStore();const authority=new HeroRuntimeEvidenceAuthority(store,()=>999);await expect(authority.accept(result())).rejects.toThrow(/timestamp/);await expect(authority.consume('bad','b'.repeat(64),'cert')).rejects.toThrow(/SHA-256/);});
});
