import {HERO_ANDROID_MIN_SAMPLE_FRAMES} from './hero-runtime-android-profile-v16.domain';
import {HERO_ANDROID_SOURCE_SCHEMA,HeroAndroidRuntimeSource,HeroAndroidSourceToken} from './hero-runtime-android-source-v21.domain';

const device={manufacturer:'Reference',model:'Android-mid',androidApi:30,gpu:'Reference GPU',renderer:'Vulkan'};
const build={appVersion:'1.0.0',commitSha:'a'.repeat(40),runtimeBundleSha256:'b'.repeat(64)};
const nonce='1'.repeat(64);
const clock=()=>{let now=1000;return ()=>now++;};
const fill=(source:HeroAndroidRuntimeSource,token:HeroAndroidSourceToken,start=0)=>{let sequence=start;for(let i=0;i<HERO_ANDROID_MIN_SAMPLE_FRAMES;i++)source.recordFrame(token,sequence++,i<570?16:24);source.recordMemory(token,sequence++,{javaBytes:10,nativeBytes:20,gpuBytes:30});return sequence;};

describe('Hero Android runtime source v21',()=>{
 it('binds raw renderer callbacks to one session token and ordered evidence',()=>{const source=new HeroAndroidRuntimeSource(device,build,clock(),()=>nonce);const token=source.issueToken();expect(token).toEqual(expect.objectContaining({schema:HERO_ANDROID_SOURCE_SCHEMA,nonce}));const next=fill(source,token);expect(next).toBe(601);const result=source.finish(1800,600);expect(result.profile.measurement.frames).toBe(600);expect(result.sourceReceipts).toHaveLength(601);expect(result.sourceReceipts[0]).toEqual(expect.objectContaining({sequence:0,kind:'frame'}));expect(result.sourceReceipts[600]).toEqual(expect.objectContaining({sequence:600,kind:'memory'}));expect(result.sourceEvidenceSha256).toMatch(/^[a-f0-9]{64}$/);});
 it('rejects a token from another source without consuming sequence',()=>{const a=new HeroAndroidRuntimeSource(device,build,clock(),()=>nonce);const b=new HeroAndroidRuntimeSource(device,build,clock(),()=> '2'.repeat(64));const foreign=b.issueToken();expect(()=>a.recordFrame(foreign,0,16)).toThrow(/does not belong/);expect(a.snapshot()).toEqual(expect.objectContaining({callbacks:0,nextSequence:0}));a.recordFrame(a.issueToken(),0,16);expect(a.snapshot().nextSequence).toBe(1);});
 it('rejects replayed, skipped and non-integer callback sequences',()=>{const source=new HeroAndroidRuntimeSource(device,build,clock(),()=>nonce);const token=source.issueToken();source.recordFrame(token,0,16);expect(()=>source.recordFrame(token,0,16)).toThrow(/must be 1/);expect(()=>source.recordFrame(token,2,16)).toThrow(/must be 1/);expect(()=>source.recordFrame(token,1.5,16)).toThrow(/must be 1/);expect(source.snapshot().nextSequence).toBe(1);});
 it('does not consume a sequence when the underlying sample is invalid',()=>{const source=new HeroAndroidRuntimeSource(device,build,clock(),()=>nonce);const token=source.issueToken();expect(()=>source.recordFrame(token,0,Number.NaN)).toThrow(/invalid/);expect(source.snapshot()).toEqual(expect.objectContaining({callbacks:0,nextSequence:0}));source.recordFrame(token,0,16);expect(source.snapshot().nextSequence).toBe(1);});
 it('freezes the issued token copy and rejects writes after finish',()=>{const source=new HeroAndroidRuntimeSource(device,build,clock(),()=>nonce);const token=source.issueToken();fill(source,token);const result=source.finish(1800,600);token.nonce='f'.repeat(64);expect(result.sourceEvidenceSha256).toMatch(/^[a-f0-9]{64}$/);expect(()=>source.recordFrame(source.issueToken(),601,16)).toThrow(/finished/);expect(()=>source.finish(1800,600)).toThrow(/finished/);});
 it('rejects malformed token entropy at construction',()=>{expect(()=>new HeroAndroidRuntimeSource(device,build,clock(),()=> 'short')).toThrow(/256 bits/);});
});
