import { AVATAR_CANONICAL_SKELETON } from './avatar-asset-manifest.domain';
import { HERO_BLOCKOUT_ASSET_KEY,HERO_BLOCKOUT_REPORT_VERSION,HERO_DNA_MORPH_NAMES,HERO_EXPRESSION_MORPH_NAMES,HERO_COMBINATION_CASE_NAMES,HeroBlockoutReport,validateHeroBlockoutReport } from './hero-blockout-report-v11.domain';
const valid=():HeroBlockoutReport=>({reportVersion:HERO_BLOCKOUT_REPORT_VERSION,assetKey:HERO_BLOCKOUT_ASSET_KEY,unitSystem:'METERS',authoringUpAxis:'Z',runtimeUpAxis:'Y',pose:'A_POSE',poseVerified:true,measuredLeftUpperArmAngleDeg:40,measuredRightUpperArmAngleDeg:40,centeredWorldOrigin:true,measuredBodyCenterX:0,groundContactY:0,measuredGroundContactMeters:0,groundContactVerified:true,bodyHeightMeters:1.68,skeletonTarget:AVATAR_CANONICAL_SKELETON,stableVertexOrder:true,deformationTopologyReady:true,skinningVerified:true,measuredUnweightedBodyVertices:0,measuredMaxBodyBoneInfluences:4,measuredMaxBodyWeightSumError:.001,uvVerified:true,measuredBodyUvLayers:1,measuredBodyUvOutOfBoundsLoops:0,pbrMaterialsVerified:true,measuredMaterialSlots:3,measuredMaxMaterialsPerObject:1,texturesVerified:true,bodyBaseColorTextureVerified:true,bodyNormalTextureVerified:true,bodyOrmTextureVerified:true,textureColorSpacesVerified:true,measuredTextureCount:3,measuredMaxTextureDimension:2048,measuredTotalTexturePixels:12582912,dnaMorphsVerified:true,dnaMorphNames:[...HERO_DNA_MORPH_NAMES],measuredDnaMorphCount:HERO_DNA_MORPH_NAMES.length,measuredMaxDnaVertexDeltaMeters:.12,expressionsVerified:true,expressionMorphNames:[...HERO_EXPRESSION_MORPH_NAMES],measuredExpressionMorphCount:HERO_EXPRESSION_MORPH_NAMES.length,measuredMaxExpressionVertexDeltaMeters:.04,combinedDeformationsVerified:true,combinationCaseNames:[...HERO_COMBINATION_CASE_NAMES],measuredCombinationCaseCount:HERO_COMBINATION_CASE_NAMES.length,measuredMaxCombinedVertexDeltaMeters:.2,measuredMaxSelfIntersectionCount:0,objects:[{role:'BODY',vertices:30000,triangles:45000,manifold:true,unappliedTransforms:false,fusedClothingOrAccessories:false},{role:'EYE_L',vertices:800,triangles:1400,manifold:true,unappliedTransforms:false,fusedClothingOrAccessories:false},{role:'EYE_R',vertices:800,triangles:1400,manifold:true,unappliedTransforms:false,fusedClothingOrAccessories:false}]});
describe('Hero v11 combined deformation production gate',()=>{
 it('accepts canonical measured stress evidence',()=>expect(validateHeroBlockoutReport(valid())).toBeDefined());
 it('still enforces v10 expressions',()=>{const x=valid();x.expressionsVerified=false as true;expect(()=>validateHeroBlockoutReport(x)).toThrow(/expression evidence/);});
 it('rejects forged combination verification',()=>{const x=valid();x.combinedDeformationsVerified=false as true;expect(()=>validateHeroBlockoutReport(x)).toThrow(/combined deformation evidence/);});
 it('rejects reordered stress cases',()=>{const x=valid();x.combinationCaseNames=[...HERO_COMBINATION_CASE_NAMES].reverse();expect(()=>validateHeroBlockoutReport(x)).toThrow(/stress matrix/);});
 it('rejects invented client stress cases',()=>{const x=valid();x.combinationCaseNames[0]='skip_collision_qa';expect(()=>validateHeroBlockoutReport(x)).toThrow(/stress matrix/);});
 it('rejects falsified case count',()=>{const x=valid();x.measuredCombinationCaseCount=999;expect(()=>validateHeroBlockoutReport(x)).toThrow(/case count/);});
 it('rejects malformed case count',()=>{const x=valid();(x as any).measuredCombinationCaseCount='6';expect(()=>validateHeroBlockoutReport(x)).toThrow(/case count/);});
 it('rejects combined displacement above 42cm',()=>{const x=valid();x.measuredMaxCombinedVertexDeltaMeters=.420001;expect(()=>validateHeroBlockoutReport(x)).toThrow(/displacement budget/);});
 it('rejects NaN combined displacement',()=>{const x=valid();x.measuredMaxCombinedVertexDeltaMeters=Number.NaN;expect(()=>validateHeroBlockoutReport(x)).toThrow(/displacement budget/);});
 it('rejects any non-adjacent self intersection',()=>{const x=valid();x.measuredMaxSelfIntersectionCount=1;expect(()=>validateHeroBlockoutReport(x)).toThrow(/self-intersections/);});
 it('rejects malformed intersection evidence',()=>{const x=valid();(x as any).measuredMaxSelfIntersectionCount='0';expect(()=>validateHeroBlockoutReport(x)).toThrow(/self-intersections/);});
 it('rejects unknown client fields through inherited exact-key validation',()=>{const x=valid();(x as any).clientCollisionApproved=true;expect(()=>validateHeroBlockoutReport(x)).toThrow(/unsupported field/);});
});
