import {AVATAR_CANONICAL_SKELETON} from './avatar-asset-manifest.domain';
import {HERO_BLOCKOUT_ASSET_KEY,HERO_DNA_MORPH_NAMES,HERO_EXPRESSION_MORPH_NAMES,HeroBlockoutReport} from './hero-blockout-report-v12.domain';
import {HERO_RUNTIME_BUNDLE_VERSION,HERO_RUNTIME_MORPH_TARGETS,HeroRuntimeBundle,inspectHeroRuntimeGlb,sha256RuntimeBytes,validateHeroRuntimeBundle,verifyHeroRuntimeBundleBytes} from './hero-runtime-bundle-v13.domain';

const LOD_VERTICES=[30000,15000,6000] as const,LOD_TRIANGLES=[50000,25000,10000] as const;
const sourceReport=():HeroBlockoutReport=>({
 reportVersion:12,assetKey:HERO_BLOCKOUT_ASSET_KEY,unitSystem:'METERS',authoringUpAxis:'Z',runtimeUpAxis:'Y',pose:'A_POSE',geometryMeasured:true,sourceObjectNames:['BODY','EYE_L','EYE_R'],stableVertexOrder:true,deformationTopologyReady:true,centeredAtWorldOrigin:true,bodyVertices:1000,bodyTriangles:1800,totalVertices:1200,totalTriangles:2000,skinningVerified:true,canonicalArmatureName:'Armature',measuredMaxBonesPerVertex:4,requiredBoneNames:[],uvVerified:true,bodyUvLayerName:'UVMap',bodyUvCoverage:1,bodyUvOverlapRatio:0,pbrVerified:true,pbrMaterialNames:[],pbrMaxTextureResolution:2048,pbrMissingTextureSlots:[],dnaMorphsVerified:true,dnaMorphNames:[...HERO_DNA_MORPH_NAMES],measuredDnaMorphCount:HERO_DNA_MORPH_NAMES.length,measuredMaxDnaVertexDeltaMeters:0.1,expressionsVerified:true,expressionMorphNames:[...HERO_EXPRESSION_MORPH_NAMES],measuredExpressionMorphCount:HERO_EXPRESSION_MORPH_NAMES.length,measuredMaxExpressionVertexDeltaMeters:0.05,combinedDeformationsVerified:true,combinationCaseNames:['body_tall_wide','torso_hips','face_wide_smile','nose_pucker','eyes_blink_brows','jaw_frown'],measuredCombinationCaseCount:6,measuredMaxCombinedVertexDeltaMeters:0.2,measuredMaxSelfIntersectionCount:0,lodsVerified:true,lodCanonicalArmatureName:'Armature',lodShapeKeyNames:['Basis',...HERO_DNA_MORPH_NAMES,...HERO_EXPRESSION_MORPH_NAMES],lodMetrics:[{level:0,objectName:'BODY_LOD0',vertices:30000,triangles:50000,maxBonesPerVertex:4,reductionFromPrevious:0},{level:1,objectName:'BODY_LOD1',vertices:15000,triangles:25000,maxBonesPerVertex:4,reductionFromPrevious:0.5},{level:2,objectName:'BODY_LOD2',vertices:6000,triangles:10000,maxBonesPerVertex:4,reductionFromPrevious:0.6}]
} as HeroBlockoutReport);

const makeGlb=(vertices:number,triangles:number,targetNames:string[]=[...HERO_RUNTIME_MORPH_TARGETS],mutate?:(doc:any)=>void)=>{
 const accessors=[{count:vertices,type:'VEC3',componentType:5126},{count:vertices,type:'VEC4',componentType:5123},{count:vertices,type:'VEC4',componentType:5126},{count:triangles*3,type:'SCALAR',componentType:5125},{count:vertices,type:'VEC3',componentType:5126}];
 const doc:any={asset:{version:'2.0'},accessors,skins:[{joints:[0]}],meshes:[{extras:{targetNames},primitives:[{mode:4,indices:3,attributes:{POSITION:0,JOINTS_0:1,WEIGHTS_0:2},targets:targetNames.map(()=>({POSITION:4}))}]}]};mutate?.(doc);
 const raw=new TextEncoder().encode(JSON.stringify(doc));const padded=(raw.length+3)&~3;const out=new Uint8Array(20+padded);const view=new DataView(out.buffer);
 view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,out.byteLength,true);view.setUint32(12,padded,true);view.setUint32(16,0x4e4f534a,true);out.fill(0x20,20);out.set(raw,20);return out;
};
const bytes=LOD_VERTICES.map((v,i)=>makeGlb(v,LOD_TRIANGLES[i]));
const bundle=():HeroRuntimeBundle=>({bundleVersion:HERO_RUNTIME_BUNDLE_VERSION,assetKey:HERO_BLOCKOUT_ASSET_KEY,format:'GLB',skeletonKey:AVATAR_CANONICAL_SKELETON,morphTargets:[...HERO_DNA_MORPH_NAMES,...HERO_EXPRESSION_MORPH_NAMES],sourceReport:sourceReport(),lods:bytes.map((b,i)=>({level:i as 0|1|2,fileName:`knowme-hero-lod${i}.glb`,sha256:sha256RuntimeBytes(b),downloadBytes:b.byteLength,vertices:LOD_VERTICES[i],triangles:LOD_TRIANGLES[i]}))});
const replace=(b:HeroRuntimeBundle,index:number,forged:Uint8Array)=>{b.lods[index].sha256=sha256RuntimeBytes(forged);b.lods[index].downloadBytes=forged.byteLength;return new Map(b.lods.map((l,i)=>[l.fileName,i===index?forged:bytes[i]]));};

describe('Hero runtime bundle v13',()=>{
 it('accepts certified manifest bound to structurally valid GLB bytes',()=>{const b=bundle();expect(validateHeroRuntimeBundle(b)).toBe(b);expect(verifyHeroRuntimeBundleBytes(b,new Map(b.lods.map((l,i)=>[l.fileName,bytes[i]]))).toBe(true);});
 it('recomputes geometry from GLB accessors',()=>expect(inspectHeroRuntimeGlb(bytes[0])).toEqual({meshCount:1,skinCount:1,morphTargetCount:HERO_RUNTIME_MORPH_TARGETS.length,vertices:30000,triangles:50000}));
 it('rejects substituted GLB bytes',()=>{const b=bundle();const files=new Map(b.lods.map((l,i)=>[l.fileName,bytes[i]]));files.set('knowme-hero-lod1.glb',new Uint8Array([9,9]));expect(()=>verifyHeroRuntimeBundleBytes(b,files)).toThrow();});
 it('rejects forged geometry copied into runtime manifest',()=>{const b=bundle();b.lods[1].triangles++;expect(()=>validateHeroRuntimeBundle(b)).toThrow(/geometry/);});
 it('rejects non-canonical manifest morph ordering',()=>{const b=bundle();b.morphTargets.reverse();expect(()=>validateHeroRuntimeBundle(b)).toThrow(/morph/);});
 it('rejects structurally forged GLB even when hash and length are self-consistent',()=>{const b=bundle();const forged=makeGlb(15000,25000,[...HERO_RUNTIME_MORPH_TARGETS].reverse());expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,1,forged))).toThrow(/morph targets/);});
 it('rejects accessor geometry forged with a self-consistent digest',()=>{const b=bundle();const forged=makeGlb(14999,25000);expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,1,forged))).toThrow(/geometry mismatch/);});
 it('rejects malformed skin accessor contracts',()=>{const b=bundle();const forged=makeGlb(6000,10000,undefined,doc=>{doc.accessors[1].type='VEC3';});expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,2,forged))).toThrow(/JOINTS_0/);});
 it('rejects morph accessors with a different vertex domain',()=>{const b=bundle();const forged=makeGlb(6000,10000,undefined,doc=>{doc.accessors[4].count=5999;});expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,2,forged))).toThrow(/morph POSITION/);});
 it('rejects non-triangle index streams',()=>{const b=bundle();const forged=makeGlb(6000,10000,undefined,doc=>{doc.accessors[3].count=29999;});expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,2,forged))).toThrow(/indices/);});
 it('rejects non-GLB payload even with matching manifest digest',()=>{const b=bundle();const forged=new Uint8Array(32);expect(()=>verifyHeroRuntimeBundleBytes(b,replace(b,2,forged))).toThrow(/not a GLB/);});
 it('rejects extra runtime files',()=>{const b=bundle();const files=new Map(b.lods.map((l,i)=>[l.fileName,bytes[i]]));files.set('evil.glb',new Uint8Array([1]));expect(()=>verifyHeroRuntimeBundleBytes(b,files)).toThrow(/exactly three|Unexpected/);});
});
